# yaml-language-server: $schema=https://json.schemastore.org/chart.json
apiVersion: v2
type: application
name: homer
description: A Helm chart for Homer
version: 2.1.0
# renovate: image=ghcr.io/bastienwirtz/homer
appVersion: "v24.05.1"

home: https://charts.pascaliske.dev/charts/homer/
sources:
  - https://github.com/pascaliske/helm-charts
  - https://github.com/bastienwirtz/homer
keywords:
  - dashboard
  - homer
maintainers:
  - name: pascaliske
    email: info@pascaliske.dev
    url: https://pascaliske.dev

dependencies:
  - name: base
    version: 1.2.0
    repository: https://charts.pascaliske.dev

annotations:
  # possible kinds: added, changed, deprecated, removed, fixed, security
  artifacthub.io/changes: |
    - kind: changed
      description: 'Changed the default image to use the GitHub container registry.'
    - kind: added
      description: 'Add support for overwriting the image registry.'
    - kind: added
      description: 'Add support for additional containers.'
    - kind: added
      description: 'Add support for affinities.'
    - kind: added
      description: 'Add support for tolerations.'
    - kind: added
      description: 'Add support for valueFrom to environment variables.'
