# yaml-language-server: $schema=https://json.schemastore.org/chart.json
apiVersion: v2
type: application
name: homer
description: A Helm chart for Homer
version: 2.1.1
# renovate: image=ghcr.io/bastienwirtz/homer
appVersion: "v24.12.1"

home: https://charts.pascaliske.dev/charts/homer/
sources:
  - https://github.com/pascaliske/helm-charts
  - https://github.com/bastienwirtz/homer
keywords:
  - dashboard
  - homer
maintainers:
  - name: pascaliske
    email: info@pascaliske.dev
    url: https://pascaliske.dev

dependencies:
  - name: base
    version: 1.2.0
    repository: https://charts.pascaliske.dev

annotations:
  # possible kinds: added, changed, deprecated, removed, fixed, security
  artifacthub.io/changes: |
    - kind: fixed
      description: 'Ensure image registry is passed to controller.'
