# yaml-language-server: $schema=https://json.schemastore.org/chart.json
apiVersion: v2
type: application
name: fritzbox-exporter
description: A Helm chart for fritzbox-exporter
version: 2.0.3
# renovate: image=sealife/fritzbox-exporter
appVersion: "1.0"

home: https://charts.alexvanderberkel.dev/charts/fritzbox-exporter/
sources:
  - https://github.com/alexvanderberkel/helm-charts
  - https://git.r3ktm8.de/SeaLife-Docker/fritzbox_exporter
keywords:
  - fritzbox-exporter
  - fritzbox
  - prometheus
  - metrics
maintainers:
  - name: alexvanderberkel
    email: alex@alex-esseling.de
    url: https://esseling.photos

dependencies:
  - name: base
    version: 1.2.0
    repository: https://charts.esseling.photos

annotations:
  # possible kinds: added, changed, deprecated, removed, fixed, security
  artifacthub.io/changes: |
    - kind: removed
      description: 'Remove values schema due to issues with flux variable substitution.'
