image:
  # -- The repository to pull the image from.
  repository: sealife/fritzbox-exporter
  # -- The docker tag, if left empty chart's appVersion will be used.
  # @default -- `.Chart.AppVersion`
  tag: ''
  # -- The pull policy for the controller.
  pullPolicy: IfNotPresent

nameOverride: ''
fullnameOverride: ''

controller:
  # -- Create a workload for this chart.
  enabled: true
  # -- Type of the workload object.
  kind: Deployment
  # -- The number of replicas.
  replicas: 1
  # -- Additional annotations for the controller object.
  annotations: {}
  # -- Additional labels for the controller object.
  labels: {}

service:
  # -- Create a service for exposing this chart.
  enabled: true
  # -- The service type used.
  type: ClusterIP
  # -- Additional annotations for the service object.
  annotations: {}
  # -- Additional labels for the service object.
  labels: {}

serviceMonitor:
  # -- Create a service monitor for prometheus operator.
  enabled: true
  # -- How frequently the exporter should be scraped.
  interval: 30s
  # -- Timeout value for individual scrapes.
  timeout: 10s
  # -- Additional annotations for the service monitor object.
  annotations: {}
  # -- Additional labels for the service monitor object.
  labels: {}

env:
  # -- Timezone for the container.
  - name: TZ
    value: UTC

ports:
  metrics:
    # -- Enable the port inside the `controller` and `Service` objects.
    enabled: true
    # -- The port used as internal port and cluster-wide port if `.service.type` == `ClusterIP`.
    port: 8765
    # -- The protocol used for the service.
    protocol: TCP

serviceAccount:
  # -- Specify the service account used for the controller.
  name: ''

# -- Compute resources used by the container. More info [here](https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/).
resources: {}
  # requests:
  #   cpu: 100m
  #   memory: 128Mi
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
