# project
site_name: Helm Charts
site_description: Another repository with lightweight Helm Charts.
site_author: Alex Esseling
site_url: https://charts.esseling.photos

# repository
repo_name: alexvanderberkel/helm-charts
repo_url: https://github.com/alexvanderberkel/helm-charts

# theme
theme:
  name: material
  logo: assets/logo.svg
  favicon: assets/favicon.png
  language: en
  palette:
    - scheme: default
      media: "(prefers-color-scheme: light)"
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode
    - scheme: slate
      primary: lime
      accent: lime
      media: "(prefers-color-scheme: dark)"
      toggle:
        icon: material/brightness-7
        name: Switch to light mode
  font:
    text: Lato
    code: Source Code Pro
  icon:
    repo: fontawesome/brands/github
  features:
    - content.code.annotate
    - content.tabs.link
    - navigation.footer
    - navigation.instant
    - navigation.sections
    - navigation.tracking
    - navigation.top
    - toc.follow
    - toc.integrate

# navigation
nav:
  - Introduction: index.md
  - Charts:
      - fritzbox-exporter: charts/fritzbox-exporter.md
      - paperless: charts/paperless.md
      - redis: charts/redis.md
      - vaultwarden: charts/vaultwarden.md
      - vikunja: charts/vikunja.md

# socials
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/alexvanderberkel
  analytics:
    provider: plausible
    domain: charts.esseling.photos
    src: https://analytics.esseling.photos/js/script.outbound-links.js
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: happy
          note: >-
            Thanks for your feedback!

        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: sad
          note: >-
            Thanks for your feedback! Help me improve this page by
            opening a <a href="https://github.com/alexvanderberkel/helm-charts/issues/new" target="_blank" rel="noopener">issue on GitHub</a>.

# customizations
extra_css:
  - styles/custom.css

# additional plugins
plugins:
  - search
  - social
  - material-plausible

# code highlighting
markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.tabbed:
      alternate_style: true
