{{- if and .Values.serviceMonitor.enabled (.Capabilities.APIVersions.Has "monitoring.coreos.com/v1") -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "uptime-kuma.fullname" . }}
  labels:
    {{- include "uptime-kuma.labels" . | nindent 4 }}
    {{- with .Values.service.labels }}
    {{ toYaml . | indent 4 }}
    {{- end }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  endpoints:
    {{- range $key, $val := .Values.ports }}
    {{- if $val.enabled }}
    - targetPort: {{ $key | quote }}
      path: /metrics
      {{- with $.Values.serviceMonitor.interval }}
      interval: {{ . }}
      {{- end }}
      {{- with $.Values.serviceMonitor.timeout }}
      scrapeTimeout: {{ . }}
      {{- end }}
    {{- end }}
    {{- end }}
  jobLabel: {{ include "uptime-kuma.fullname" . }}
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  selector:
    matchLabels:
      {{- include "uptime-kuma.selectorLabels" . | nindent 6 }}
{{- end }}
