apiVersion: v2
type: application
name: digitalocean-dyndns
description: A Helm chart for a CronJob based DigitalOcean DynDNS client.
version: 0.2.5
# renovate: image=ghcr.io/pascaliske/digitalocean-dyndns
appVersion: "0.0.3"

home: https://charts.pascaliske.dev/charts/digitalocean-dyndns/
sources:
  - https://github.com/pascaliske/helm-charts
  - https://github.com/pascaliske/docker-digitalocean-dyndns
keywords:
  - digitalocean
  - dyndns
maintainers:
  - name: pascaliske
    email: info@pascaliske.dev
    url: https://pascaliske.dev

annotations:
  # possible kinds: added, changed, deprecated, removed, fixed, security
  artifacthub.io/changes: |
    - kind: removed
      description: 'Remove values schema due to issues with flux variable substitution.'
