# yaml-language-server: $schema=https://json.schemastore.org/chart.json
apiVersion: v2
type: application
name: vikunja
description: A Helm chart for Kubernetes
version: 5.0.0
# renovate: image=vikunja/vikunja
appVersion: "0.24.6"

home: https://charts.pascaliske.dev/charts/vikunja/
sources:
  - https://github.com/pascaliske/helm-charts
  - https://code.vikunja.io
  - https://vikunja.io
keywords:
  - vikunja
  - todos
maintainers:
  - name: pascaliske
    email: info@pascaliske.dev
    url: https://pascaliske.dev

dependencies:
  - name: base
    version: 1.2.0
    repository: https://charts.pascaliske.dev

annotations:
  # possible kinds: added, changed, deprecated, removed, fixed, security
  artifacthub.io/changes: |
    - kind: changed
      description: 'Switch to new combined vikunja image.'
