# yaml-language-server: $schema=https://json.schemastore.org/chart.json
apiVersion: v2
type: application
name: pairdrop
description: A Helm chart for PairDrop
version: 1.0.2
# renovate: image=ghcr.io/linuxserver/pairdrop
appVersion: "version-v1.11.2"

home: https://charts.pascaliske.dev/charts/pairdrop/
sources:
  - https://github.com/pascaliske/helm-charts
  - https://github.com/linuxserver/docker-pairdrop
  - https://github.com/schlagmichdoch/PairDrop
keywords:
  - pairdrop
  - airdrop
maintainers:
  - name: pascaliske
    email: info@pascaliske.dev
    url: https://pascaliske.dev

dependencies:
  - name: base
    version: 1.2.0
    repository: https://charts.pascaliske.dev

annotations:
  # possible kinds: added, changed, deprecated, removed, fixed, security
  artifacthub.io/changes: |
    - kind: fixed
      description: 'Configure startup probe to ensure container has enough time to be started.'
