{{/* Append the hardcoded settings */}}
{{- define "gotify.harcodedValues" -}}
controllers:
  main:
    containers:
      main:
        env:
          GOTIFY_SERVER_PORT: {{ .Values.service.main.ports.http.port }}
          GOTIFY_DATABASE_DIALECT: sqlite3
          GOTIFY_DATABASE_CONNECTION: /app/data/gotify.db
{{- end -}}
{{- $_ := mergeOverwrite .Values (include "gotify.harcodedValues" . | fromYaml) -}}

{{/* Render the templates */}}
{{ include "bjw-s.common.loader.all" . }}