# yaml-language-server: $schema=https://json.schemastore.org/chart.json
apiVersion: v2
type: application
name: hammond
description: A Helm chart for hammond
version: 1.0.0
# renovate: image=ghcr.io/alfhou/hammond
appVersion: "v0.0.24"

home: https://charts.pascaliske.dev/charts/hammond/
sources:
  - https://github.com/pascaliske/helm-charts
  - https://github.com/AlfHou/hammond
keywords:
  - hammond
  - vehicle-management
  - expenses-management
maintainers:
  - name: pascaliske
    email: info@pascaliske.dev
    url: https://pascaliske.dev

dependencies:
  - name: base
    version: 1.2.0
    repository: https://charts.pascaliske.dev

annotations:
  # possible kinds: added, changed, deprecated, removed, fixed, security
  artifacthub.io/changes: |
    - kind: removed
      description: 'Remove support for CRDs from "traefik.containo.us".'
    - kind: added
      description: 'Add support for CRDs from "traefik.io".'
