# yaml-language-server: $schema=https://json.schemastore.org/chart.json
apiVersion: v2
type: application
name: clickhouse
description: A Helm chart for ClickHouse
version: 0.3.0
# renovate: image=clickhouse/clickhouse-server
appVersion: "24.6.3.47-alpine"

home: https://charts.pascaliske.dev/charts/clickhouse/
sources:
  - https://github.com/pascaliske/helm-charts
  - https://github.com/clickhouse/clickhouse
  - https://clickhouse.com
keywords:
  - clickhouse
maintainers:
  - name: pascaliske
    email: info@pascaliske.dev
    url: https://pascaliske.dev

dependencies:
  - name: base
    version: 1.2.0
    repository: https://charts.pascaliske.dev

annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: 'Updated config XMLs to latest versions.'
