# yaml-language-server: $schema=https://json.schemastore.org/chart.json
apiVersion: v2
type: application
name: snapdrop
description: A Helm chart for snapdrop
version: 3.0.0
# renovate: image=ghcr.io/linuxserver/snapdrop
appVersion: "version-724f0af5"
deprecated: true

home: https://charts.pascaliske.dev/charts/snapdrop/
sources:
  - https://github.com/pascaliske/helm-charts
  - https://github.com/linuxserver/docker-snapdrop
  - https://github.com/RobinLinus/snapdrop
keywords:
  - snapdrop
  - airdrop

dependencies:
  - name: base
    version: 1.2.0
    repository: https://charts.pascaliske.dev

annotations:
  # possible kinds: added, changed, deprecated, removed, fixed, security
  artifacthub.io/changes: |
    - kind: deprecated
      description: 'Original project snapdrop was acquired by some company that ruined it. Switch to PairDrop instead.'
